CREATE TABLE IF NOT EXISTS file
(
    id       INT AUTO_INCREMENT PRIMARY KEY,
    name     VARCHAR(128) NOT NULL,
    filepath VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS user
(
    id   INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS event
(
    id      INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    file_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE,
    FOREIGN KEY (file_id) REFERENCES file (id) ON DELETE CASCADE
);

